[{"title":"Introduction","type":0,"sectionRef":"#","url":"/roact-error-boundary/docs/intro","content":"","keywords":""},{"title":"Installation​","type":1,"pageTitle":"Introduction","url":"/roact-error-boundary/docs/intro#installation","content":""},{"title":"Wally​","type":1,"pageTitle":"Introduction","url":"/roact-error-boundary/docs/intro#wally","content":"roact-spring supports Roact17. However, Legacy Roact is not supported. To install, add the latest version of roact-error-boundary to your wally.toml: RoactSpring = &quot;chriscerie/react-spring@&lt;version&gt;&quot;  "},{"title":"Error","type":0,"sectionRef":"#","url":"/roact-error-boundary/api/Error","content":"On this page Error A LuauPolyFill.Error object to represent errors produced. { message: string, name: string, stack: string, } ","keywords":""},{"title":"ReactErrorBoundary","type":0,"sectionRef":"#","url":"/roact-error-boundary/api/ReactErrorBoundary","content":"","keywords":""},{"title":"Types​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#types","content":" "},{"title":"ErrorBoundaryContextType​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#ErrorBoundaryContextType","content":"&lt;/&gt; interface ErrorBoundaryContextType { didCatch: boolean error: any resetErrorBoundary: (...any) → () }   "},{"title":"FallbackProps​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#FallbackProps","content":"&lt;/&gt; interface FallbackProps { error: Error resetErrorBoundary: (...any) → ()-- Resets the error boundary and calls onReset if provided. This is useful for reverting state or retrying the render. } Props for fallback components. Fallback components should be typed like: local Fallback: React.FC&lt;ReactErrorBoundary.FallbackProps&gt; = function(props) -- ... end   "},{"title":"UseErrorBoundaryApi​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#UseErrorBoundaryApi","content":"&lt;/&gt; interface UseErrorBoundaryApi { resetBoundary: () → () showBoundary: (error: Error) → () }  "},{"title":"Functions​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#functions","content":" "},{"title":"ErrorBoundary​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#ErrorBoundary","content":"&lt;/&gt; ReactErrorBoundary.ErrorBoundary() → () This is a React component. Wrap an ErrorBoundary around other React components to &quot;catch&quot; errors and render a fallback UI. The component supports several ways to render a fallback (shown below). First, create a fallback component. local e = React.createElement local Fallback: React.FC&lt;ReactErrorBoundary.FallbackProps&gt; = function(_props) return e(&quot;TextLabel&quot;, { AnchorPoint = Vector2.new(0.5, 0.5), Size = UDim2.fromScale(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.5), Text = &quot;An error was encountered!.&quot;, }) end Next, in your other components, wrap in an ErrorBoundary where needed. When an error is encountered somewhere in your app, the nearest ErrorBoundary will catch and handle it. You don't need to wrap every component in an ErrorBoundary. Consider the granularity of error boundaries and where it makes sense to display an error message or revert states. Using FallbackComponent prop See ErrorIn1SecondFallbackComponent for a full example. return e(ReactErrorBoundary.ErrorBoundary, { FallbackComponent = Fallback, }, { ComponentThatErrors = e(ComponentThatErrors), }) Using fallbackRender prop Render prop function that returns the fallback UI. This is helpful if you want to handle errors differently based on the error. See ErrorIn1SecondFallbackComponent for a full example. caution Render prop functions are normal functions and are not React components. Attempting to use hooks in them will error! return e(ReactErrorBoundary.ErrorBoundary, { fallbackRender = function(props: ReactErrorBoundary.FallbackProps) return e(Fallback) end, }, { ComponentThatErrors = e(ComponentThatErrors), }) Using fallback prop See ErrorIn1SecondFallback for a full example. caution This creates the fallback element even when it's not needed. return e(ReactErrorBoundary.ErrorBoundary, { fallback = e(Fallback), }, { ComponentThatErrors = e(ComponentThatErrors), }) onError When passed, onError gets called when an error is caught. This is useful for logging errors. return e(ReactErrorBoundary.ErrorBoundary, { FallbackComponent = Fallback, onError = function(error: LuauPolyfill.Error, info: { componentStack: string }) warn(&quot;Caught error:&quot;, error, info) end, }, { ComponentThatErrors = e(ComponentThatErrors), }) onReset When passed, onReset gets called when the error boundary is reset by a call to resetErrorBoundary or when the resetKeys change. This is useful for reverting state. See ResetCount for a full example. return e(ReactErrorBoundary.ErrorBoundary, { FallbackComponent = Fallback, onReset = function( details: { reason: &quot;imperative-api&quot;, args: { any } } | { reason: &quot;keys&quot;, prev: { any }?, next: { any }? } ) warn(&quot;Error boundary was reset:&quot;, details) end, }, { ComponentThatErrors = e(ComponentThatErrors), })   "},{"title":"useErrorBoundary​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#useErrorBoundary","content":"&lt;/&gt; ReactErrorBoundary.useErrorBoundary() → () TODO: Undocumented  "},{"title":"withErrorBoundary​","type":1,"pageTitle":"ReactErrorBoundary","url":"/roact-error-boundary/api/ReactErrorBoundary#withErrorBoundary","content":"&lt;/&gt; ReactErrorBoundary.withErrorBoundary() → () TODO: Undocumented "}]